apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-forecast-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: weather-forecast
  template:
    metadata:
      labels:
        app: weather-forecast
        zone: prod
        version: v1
    spec:
      containers:
        - name: dockertest
          image:  m4manugoel/dockertest-web_service:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                configMapKeyRef:
                  name: weatherforecast-database-config
                  key: connection_string              
